from pgvector import Vector
from psycopg import sql
from psycopg.rows import class_row
from psycopg_pool import ConnectionPool

from app.domain.docs import Chunk, ParsedDoc, RetrievedChunk
from app.repositories.base import ChunkSearcher, KnowledgeWriter, ChunkToEmbed, EmbeddingFiller
from app.repositories import queries


class PostgresRepository(ChunkSearcher, KnowledgeWriter, EmbeddingFiller):
    """Reads and writes documents, chunks and vectors in PostgreSQL.

    Every vector handed to psycopg is wrapped in ``pgvector.Vector``. Without
    that wrapper the driver serializes a Python list as a PostgreSQL array,
    which the ``vector`` column rejects with a type error that does not
    obviously point at the real cause.
    """

    def __init__(
        self,
        pool: ConnectionPool,
        embedding_model: str,
        embeddings_table: str = "chunk_embeddings",
    ) -> None:
        """Bind the adapter to a pool, a model name and a vector table.

        Args:
            pool: Connection pool, already configured to register the
                pgvector types on each connection.
            embedding_model: Name of the model producing the vectors. It is
                written on every row and filtered on every search, which is
                what keeps separate embedding spaces from mixing.
            embeddings_table: Table holding the vectors. It is quoted as an
                SQL identifier, so an alternative embedding space can live
                in a second table during a model migration.
        """
        self._pool = pool
        self._embedding_model = embedding_model
        self._embeddings_table = sql.Identifier(embeddings_table)

    def save_document(self, doc: ParsedDoc, chunks: list[Chunk], embeddings: list[list[float]]) -> None:
        """Persist a document with its chunks and vectors, idempotently.

        The document row is upserted, then its chunks are deleted and
        rewritten, which is why re-ingesting an unchanged corpus converges on
        the same state instead of accumulating duplicates. Deleting the
        chunks also drops their vectors through the foreign key cascade.

        Chunk ids are generated by the database, so they are read back by
        position before the vectors can be attached to the right rows.

        Everything runs inside a single pooled connection, so a failure
        partway through leaves the previous state of the document intact.

        Args:
            doc: The parsed document, raw Markdown included.
            chunks: The chunks cut from it, in document order.
            embeddings: One vector per chunk, in the same order.
        """
        with self._pool.connection() as conn:
            conn.execute(
                queries.UPSERT_DOCUMENT,
                (doc.id, doc.title, doc.category, doc.source_path, doc.raw_content)
            )
            conn.execute(
                queries.DELETE_DOCUMENT_CHUNKS,
                (doc.id,)
            )

            with conn.cursor() as cur:
                cur.executemany(
                    queries.INSERT_CHUNK,
                    [
                        (doc.id, c.chunk_index, c.section, c.content, c.token_count)
                        for c in chunks
                    ]
                )

                cur.execute(
                    queries.CHUNK_IDS_BY_INDEX,
                    (doc.id,)
                )

                id_by_index = dict(cur.fetchall())

                cur.executemany(
                    queries.INSERT_EMBEDDING.format(self._embeddings_table),
                    [
                        (id_by_index[c.chunk_index], self._embedding_model, Vector(emb))
                        for c, emb in zip(chunks, embeddings)
                    ]
                )

    def search_similar(self, query_emb: list[float], top_k: int) -> list[RetrievedChunk]:
        """Return the chunks closest to a query vector.

        Rows are mapped straight onto the domain type by ``class_row``, so
        the column aliases in the query have to keep matching the field names
        of ``RetrievedChunk``.

        Args:
            query_emb: The embedded question.
            top_k: Maximum number of results to return.

        Returns:
            Up to ``top_k`` chunks ordered by decreasing similarity. Results
            are not filtered by relevance, since applying the threshold is
            the caller's decision.
        """
        with self._pool.connection() as conn:
            with conn.cursor(row_factory=class_row(RetrievedChunk)) as cur:
                cur.execute(
                    queries.SEARCH_SIMILAR.format(self._embeddings_table),
                    (Vector(query_emb), self._embedding_model, Vector(query_emb), top_k)
                )
                return cur.fetchall()


    def chunks_to_embed(self) -> list[ChunkToEmbed]:
        """List every stored chunk together with its provenance.

        Returns:
            All chunks in the corpus, ordered by identifier, carrying the
            document title and section needed to rebuild the exact text that
            the original ingestion embedded.
        """
        with self._pool.connection() as conn:
            with conn.cursor(row_factory=class_row(ChunkToEmbed)) as cur:
                cur.execute(
                    queries.CHUNKS_TO_EMBED
                )
                return cur.fetchall()

    def save_embeddings(self, model: str, vectors: dict[int, list[float]]) -> None:
        """Write or replace vectors for chunks that already exist.

        Unlike the ingestion path, this upserts, because a backfill can be
        interrupted and resumed over rows that were already written.

        Args:
            model: Name of the model that produced the vectors. It is stored
                as part of the primary key, so vectors from different models
                coexist without overwriting one another.
            vectors: Mapping from chunk identifier to its vector.
        """
        with self._pool.connection() as conn:
            with conn.cursor() as cur:
                cur.executemany(
                    queries.UPSERT_EMBEDDING.format(self._embeddings_table),
                    [
                        (chunk_id, model, Vector(vector))
                        for chunk_id, vector in vectors.items()
                    ]
                )
